name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install pio
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run PlatformIO build on selected platforms
      run: platformio run --environment wemos_d1_mini32  --project-dir ./esp/light_box

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./esp/light_box/.pio/build/*/firmware_*.bin
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
